//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TancleClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TancleClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AdviceManagement 的本地化字符串。
        /// </summary>
        internal static string View_AdviceManagement {
            get {
                return ResourceManager.GetString("View_AdviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdviceName 的本地化字符串。
        /// </summary>
        internal static string View_AdviceManagement_AdviceName {
            get {
                return ResourceManager.GetString("View_AdviceManagement_AdviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdviceNo 的本地化字符串。
        /// </summary>
        internal static string View_AdviceManagement_AdviceNo {
            get {
                return ResourceManager.GetString("View_AdviceManagement_AdviceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input advice name to find 的本地化字符串。
        /// </summary>
        internal static string View_AdviceManagement_FindHint {
            get {
                return ResourceManager.GetString("View_AdviceManagement_FindHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AreaManagement 的本地化字符串。
        /// </summary>
        internal static string View_AreaManagement {
            get {
                return ResourceManager.GetString("View_AreaManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AreaName 的本地化字符串。
        /// </summary>
        internal static string View_AreaManagement_AreaName {
            get {
                return ResourceManager.GetString("View_AreaManagement_AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input area name to find 的本地化字符串。
        /// </summary>
        internal static string View_AreaManagement_FindHint {
            get {
                return ResourceManager.GetString("View_AreaManagement_FindHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        internal static string View_AreaManagement_Id {
            get {
                return ResourceManager.GetString("View_AreaManagement_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        internal static string View_Button_FirstPage {
            get {
                return ResourceManager.GetString("View_Button_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string View_Button_LastPage {
            get {
                return ResourceManager.GetString("View_Button_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string View_Button_NextPage {
            get {
                return ResourceManager.GetString("View_Button_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        internal static string View_Button_PreviousPage {
            get {
                return ResourceManager.GetString("View_Button_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HabitManagement 的本地化字符串。
        /// </summary>
        internal static string View_HabitManagement {
            get {
                return ResourceManager.GetString("View_HabitManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input habit name to find 的本地化字符串。
        /// </summary>
        internal static string View_HabitManagement_FindHint {
            get {
                return ResourceManager.GetString("View_HabitManagement_FindHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HabitName 的本地化字符串。
        /// </summary>
        internal static string View_HabitManagement_HabitName {
            get {
                return ResourceManager.GetString("View_HabitManagement_HabitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HabitNo 的本地化字符串。
        /// </summary>
        internal static string View_HabitManagement_HabitNo {
            get {
                return ResourceManager.GetString("View_HabitManagement_HabitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatedTime 的本地化字符串。
        /// </summary>
        internal static string View_Header_CreatedTime {
            get {
                return ResourceManager.GetString("View_Header_CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdatedTime 的本地化字符串。
        /// </summary>
        internal static string View_Header_UpdatedTime {
            get {
                return ResourceManager.GetString("View_Header_UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SickneessName 的本地化字符串。
        /// </summary>
        internal static string View_SickneessManagement_SickneessName {
            get {
                return ResourceManager.GetString("View_SickneessManagement_SickneessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SickneessNo 的本地化字符串。
        /// </summary>
        internal static string View_SickneessManagement_SickneessNo {
            get {
                return ResourceManager.GetString("View_SickneessManagement_SickneessNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SicknessManagement 的本地化字符串。
        /// </summary>
        internal static string View_SicknessManagement {
            get {
                return ResourceManager.GetString("View_SicknessManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input sicknetss name to find 的本地化字符串。
        /// </summary>
        internal static string View_SicknessManagement_FindHint {
            get {
                return ResourceManager.GetString("View_SicknessManagement_FindHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of SicknessName must less than 200 的本地化字符串。
        /// </summary>
        internal static string View_Validation_SicknessName_Length {
            get {
                return ResourceManager.GetString("View_Validation_SicknessName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of SicknessNo must less than 200 的本地化字符串。
        /// </summary>
        internal static string View_Validation_SicknessNo_Length {
            get {
                return ResourceManager.GetString("View_Validation_SicknessNo_Length", resourceCulture);
            }
        }
    }
}
